import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import { normalizeJob } from "../engine/core/job.mjs";
import { loadGraph } from "../engine/knowledge/graph.mjs";
import { compilePrompt } from "../engine/prompts/compiler.mjs";
import { runPreflight } from "../engine/quality/preflight.mjs";
import { buildHeroJob } from "../engine/brandkit/hero-job.mjs";
import { composeAd, FORMATS, RATIOS } from "../engine/brandkit/nulumin-ads.mjs";
import { dataEntries, dataKeys, listPacks, resolvePackId } from "../engine/brandkit/kit.mjs";
import { commandKit } from "../engine/brandkit/index.mjs";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const packDirectory = path.join(root, "knowledge", "brands", "nulumin");
const read = (file) => JSON.parse(fs.readFileSync(path.join(packDirectory, file), "utf8"));

const design = read("design-system.json");
const catalog = read("catalog.json");
const points = read("selling-points.json");
const heroPrompts = read("hero-prompts.json");

/** A kit with stubbed assets, so pack logic is testable without Chrome, fonts, or the network. */
const stubKit = {
  id: "nulumin",
  design,
  catalog,
  points,
  heroPrompts,
  fontCss: "/* stub */",
  fontVariables: "--font-fraunces: serif; --font-inter: sans-serif; --font-jetbrains-mono: monospace; --font-space-grotesk: sans-serif;",
  dataUri: () => "data:image/png;base64,AA==",
  trimmedDataUri: async () => "data:image/png;base64,AA==",
  assertAssets: () => {},
};

test("the nulumin pack is discoverable and resolves by alias", () => {
  assert(listPacks(root).includes("nulumin"));
  assert.equal(resolvePackId(root, "NuLumin Bio-Sciences"), "nulumin");
  assert.equal(resolvePackId(root, "brand.nulumin"), "nulumin");
});

test("every selling point names a claim record that exists on disk", () => {
  for (const [key, point] of dataEntries(points.points)) {
    const record = path.join(root, "knowledge", "claims", `${point.claim}.json`);
    assert(fs.existsSync(record), `selling point "${key}" references missing claim record ${point.claim}`);
    for (const field of ["label", "loud", "spec"]) {
      assert(point[field], `selling point "${key}" is missing its ${field} form; one ad format renders blank`);
    }
    assert.equal(point.spec.length, 2, `selling point "${key}" spec must be a pre-broken two-line pair`);
  }
});

test("claim records ship unapproved so nothing unsourced can be generated by default", () => {
  const files = fs.readdirSync(path.join(root, "knowledge", "claims")).filter((file) => file.startsWith("claim.nulumin."));
  assert(files.length > 0);
  for (const file of files) {
    const record = JSON.parse(fs.readFileSync(path.join(root, "knowledge", "claims", file), "utf8"));
    assert.equal(record.id, path.basename(file, ".json"));
    assert.equal(record.brand, "brand.nulumin");
    assert.equal(record.status, "draft", `${file} is approved but no human owner has signed it off`);
    assert(record.source.url && record.source.support && record.source.retrievedAt);
    assert(record.prohibitedUses.some((rule) => /human-use|human use/i.test(rule)));
  }
});

test("hooks and variants only reference points that exist", () => {
  for (const [key, hook] of dataEntries(points.hooks)) {
    assert.equal(hook.lines.length, 2, `hook "${key}" needs a roman clause and an italic clause`);
    for (const pointKey of hook.points) assert(points.points[pointKey], `hook "${key}" references unknown point ${pointKey}`);
    assert(points.points[hook.offer], `hook "${key}" references unknown offer ${hook.offer}`);
  }
  for (const [key, variant] of dataEntries(points.variants)) {
    assert.equal(variant.points.length, 3, `variant "${key}" must carry exactly three selling points`);
    for (const pointKey of variant.points) assert(points.points[pointKey], `variant "${key}" references unknown point ${pointKey}`);
  }
});

test("every compound maps to a real category and a present product asset", () => {
  for (const [key, compound] of dataEntries(catalog.compounds)) {
    assert(catalog.categories[compound.category], `compound "${key}" has unknown category ${compound.category}`);
    assert(catalog.capColors[compound.cap], `compound "${key}" has unknown cap color ${compound.cap}`);
    assert(catalog.cakeColors[compound.cake], `compound "${key}" has unknown cake color ${compound.cake}`);
    if (compound.vial) assert(fs.existsSync(path.join(root, compound.vial)), `compound "${key}" declares a missing vial asset`);
  }
  for (const [key, panel] of dataEntries(catalog.panels)) {
    for (const member of panel.members) assert(catalog.compounds[member], `panel "${key}" references unknown compound ${member}`);
  }
});

test("marketing and packaging palettes stay separate", () => {
  const marketing = new Set(Object.values(design.surfaces.marketing.spectrum));
  const packaging = new Set(Object.values(design.surfaces.packaging).filter((value) => value.startsWith("#")));
  for (const hex of marketing) {
    assert(!packaging.has(hex), `${hex} appears in both palettes; the two surfaces must not converge`);
  }
});

test("every format and ratio renders markup with the disclosure and no unresolved placeholder", async () => {
  for (const format of FORMATS) {
    for (const ratio of Object.keys(RATIOS)) {
      const options = format === "panel" ? { panel: "cellular", hook: "panel" } : { compound: "ghkcu" };
      const { html, width, height, meta } = await composeAd(stubKit, { format, ratio, ...options });
      assert.equal(width, RATIOS[ratio][0]);
      assert.equal(height, RATIOS[ratio][1]);
      assert(html.includes(design.disclosures.ruo), `${format} ${ratio} dropped the RUO disclosure`);
      assert.doesNotMatch(html, /\{compound\}|\{name\}|\{dose\}/, `${format} ${ratio} left a placeholder unresolved`);
      assert.equal(meta.points.length, 3);
      for (const spectrum of Object.values(design.surfaces.marketing.spectrum)) {
        assert(html.includes(spectrum), `${format} ${ratio} is missing a spectrum band segment`);
      }
    }
  }
});

test("ad copy is escaped rather than injected", async () => {
  // A shallow copy with a replaced copy deck: structuredClone cannot carry the stub's functions.
  const injected = { ...stubKit, points: JSON.parse(JSON.stringify(points)) };
  injected.points.hooks.documented.lines = ["<script>alert(1)</script>", "safe."];
  const { html } = await composeAd(injected, { format: "single", compound: "ghkcu", ratio: "1:1" });
  assert(!html.includes("<script>alert(1)</script>"));
  assert(html.includes("&lt;script&gt;"));
});

test("a generated hero job compiles and clears regulated preflight", () => {
  const graph = loadGraph(root);
  const job = normalizeJob(buildHeroJob(stubKit, { compound: "ghkcu", style: "cryo", ratio: "9:16" }));
  const { prompt, brand } = compilePrompt(job, graph);

  assert.match(prompt, /PRODUCT CONTRACT/);
  assert.match(prompt, /GHK-Cu/);
  assert.match(prompt, /BLUISH-VIOLET lyophilized cake/);
  assert.doesNotMatch(prompt, /\{name\}|\{dose\}|\{cap\}|\{cake\}|\{rules\}/);

  const result = runPreflight({ root, job, prompt, assets: [], brand });
  assert.equal(result.ok, true, JSON.stringify(result.errors));
  // The verbatim contract is long by design and must not trip the prose-bloat heuristic.
  assert(!result.warnings.some((issue) => issue.code === "PROMPT_TOO_LONG"));
});

test("a dropped hero style fails loudly with the reason it was dropped", () => {
  assert.throws(
    () => buildHeroJob(stubKit, { style: "chromatogram" }),
    (error) => error.code === "UNKNOWN_STYLE" && /rejected twice/i.test(error.message),
  );
});

test("hero prompt blocks keep the reference contract that stops label drift", () => {
  assert.match(heroPrompts.blocks.product, /REFERENCE IMAGE 2 is a HIGH-RESOLUTION CLOSE-UP OF THE LABEL/);
  assert.match(heroPrompts.blocks.empty, /THERE IS NO PRODUCT IN THIS IMAGE/);
  for (const ratio of dataKeys(heroPrompts.composition)) {
    assert.match(heroPrompts.composition[ratio], /BELOW THE VERTICAL MIDPOINT/, `${ratio} lost the centre-line rule`);
  }
});

test("the CLI orientation command runs offline and reports real asset state", async () => {
  const summary = await commandKit(root, "nulumin");
  assert.equal(summary.brand, "nulumin");
  assert.deepEqual(summary.formats, FORMATS);
  assert(summary.compounds.includes("ghkcu"));
  assert(summary.docs.includes("AD_SYSTEM.md"));
  // Patterns must not be reported as a missing file, and prose must not leak into the asset list.
  for (const asset of summary.assets) {
    assert(!asset.path.includes("{"), `${asset.key} is a pattern, not a concrete asset path`);
    assert.equal(asset.present, true, `declared asset ${asset.key} is missing from the repository`);
  }
});
