#!/usr/bin/env node
// Dialed Moods graphic generator.
//
// Makes ANY Dialed Moods graphic in the approved look, for ANY product, without editing this file.
// The whole graphic is generated by gpt-image-2 with the real can render passed as a reference.
// Never composite — see knowledge/brands/dialed-moods/FORMATS.md.
//
//   node dialed_moods_gen.mjs --list
//   node dialed_moods_gen.mjs --product cognitionBlueGlacier \
//        --eyebrow "CLEAN ENERGY" --headline "Focus you can" --gold "actually feel." \
//        --support "A nootropic seltzer built for the long afternoon." \
//        --ratio 4x5 --name focus_test
//   node dialed_moods_gen.mjs --brief my-brief.json
//   node dialed_moods_gen.mjs --preset socialElixirLaunch          (the 5 approved launch pieces)
//
// Every string you pass is reproduced verbatim. Pack copy comes from the brand pack, never typed
// here, so a graphic cannot carry another product line's numbers.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const REPO = path.dirname(fileURLToPath(import.meta.url));
const ENV = path.join(REPO, ".env");
if (fs.existsSync(ENV)) {
  for (const line of fs.readFileSync(ENV, "utf-8").split("\n")) {
    const m = line.match(/^\s*([\w]+)\s*=\s*(.+?)\s*$/);
    if (m && !process.env[m[1]]) process.env[m[1]] = m[2];
  }
}

const PACK = path.join(REPO, "knowledge", "brands", "dialed-moods");
const readPack = (f) => JSON.parse(fs.readFileSync(path.join(PACK, f), "utf-8"));
const CATALOG = readPack("catalog.json");
const PROMPTS = readPack("hero-prompts.json");
const DESIGN = readPack("design-system.json");
const ART = path.join(REPO, "Brand Context", "assets", "Dialed_Moods", "creative");
const LOGO = path.join(ART, "dialedMoodsLogo.png");
const STYLEREF = path.join(ART, "style_master_ref_1400.png");

const SIZES = PROMPTS.provider.sizes;
const products = () => Object.entries(CATALOG.compounds).filter(([k]) => !k.startsWith("$"));

// ---- args -------------------------------------------------------------------------------------
const argv = process.argv.slice(2);
const flag = (n, d = null) => { const i = argv.indexOf(`--${n}`); return i >= 0 && argv[i + 1] && !argv[i + 1].startsWith("--") ? argv[i + 1] : (argv.includes(`--${n}`) ? true : d); };

if (flag("list")) {
  console.log("\nProducts (--product <id>):\n");
  for (const [k, p] of products()) {
    const pc = CATALOG.packagingCopy[p.category];
    console.log(`  ${k.padEnd(30)} ${p.name}${pc?.specVerified === false ? "   [spec column NOT verified]" : ""}`);
  }
  console.log("\nRatios (--ratio): " + Object.keys(SIZES).join(", "));
  const presetNames = Object.keys(JSON.parse(fs.readFileSync(path.join(REPO, "dialed_moods_presets.json"), "utf-8"))).filter((k) => !k.startsWith("$"));
  console.log("Presets (--preset): " + presetNames.join(", ") + "\n");
  process.exit(0);
}

// ---- prompt assembly --------------------------------------------------------------------------
// Pack copy is injected from catalog.json, so the can contract always matches the product being
// rendered. This is the guard that stops a Cognition can being printed with Social Elixir numbers.
function canContract(product) {
  const pc = CATALOG.packagingCopy[product.category];
  const sh = CATALOG.packagingCopy.shared;
  const showSpec = pc.specVerified !== false;
  return `PRINTED COPY ON THE CAN — REPRODUCE, NEVER INVENT:
· Every word printed on the can must come from REFERENCE 1. Reproduce its side panel as it actually exists — the vertical "${sh.vertical}" line, the QR code and its three numbered app steps, the small "${sh.mark}" mark, the tagline and the nutrition column. Do not redesign, re-word or re-letter any of it.
· THESE EXACT STRINGS APPEAR ON THIS CAN AND MUST BE SPELLED CHARACTER-FOR-CHARACTER. Proof-read each one before finishing:
  "${pc.band}"   (the band under the top edge)
  "${pc.line}"
  "${pc.category}"
  "${pc.volume}"
  "${pc.subline}"
  "${sh.vertical}"
· This can is ${pc.body}. Its flavour tab reads "${product.flavourTab}".
${showSpec
  ? `· NUMERIC LOCK: the nutrition column reads EXACTLY, top to bottom: ${pc.specColumn.map((s) => `"${s}"`).join(", ")}. Never any other figure. If those numbers cannot be rendered crisply and correctly, turn that panel away from camera instead.`
  : `· CRITICAL — THE NUTRITION COLUMN ON THIS PRODUCT IS UNVERIFIED AND MUST NOT BE SHOWN. Rotate the can so that the nutrition column faces AWAY from the camera and is not visible at all, or crop it beyond the frame edge. Do not render it small, do not render it blurred, do not render it partially — render NO ingredient names and NO milligram figures anywhere on this can. Inventing or guessing a supplement fact is the single worst failure this image can have.`}
· Where printed type is genuinely too small to letter, let it fall into natural photographic softness — slightly out of focus, low contrast, the way real 4pt pack copy looks in a studio photograph. Do NOT substitute sharp scrambled pseudo-lettering for it.
· Invent nothing that is not on REFERENCE 1: no extra warning block, no extra supplement-facts table, no additional QR code, no new claims.
· ABSOLUTELY DO NOT REDESIGN THE CAN. It keeps its body finish, its bands, its big vertical italic chrome "DIALED" wordmark with the heavy gold outline and drop shadow, the small vertical "MOODS", the coloured flavour tab and the fruit artwork. A plain can with a small horizontal logo and no bands is WRONG and must never be produced.`;
}

function buildPrompt(brief, product, ratio) {
  const b = PROMPTS.blocks;
  const gold = brief.gold ? ` with "${brief.gold}" in metallic gold` : "";
  const support = (brief.support ? [].concat(brief.support) : []).map((s) => `· one line reading exactly "${s}"`).join("\n");
  const extra = brief.extra ? `\n${brief.extra}` : "";
  const scene = `ONE can standing as a large, sharp hero on the RIGHT side of the frame, lit like a jewel against a deep near-black ground washed with ${product.bloom} light, with a soft bloom behind it and a long clean reflection beneath.
The LEFT half is empty, dark, uncluttered space holding, from top to bottom:
· a small gold eyebrow reading exactly "${brief.eyebrow}"
· a large headline reading exactly "${brief.headline}${brief.gold ? " " + brief.gold : ""}"${gold}
${support}${extra}`;
  return [
    scene,
    b.brand,
    b.styleMatch,
    b.typeDepth,
    canContract(product),
    legalContract(product),
    b.spelling,
  ].join("\n\n");
}

// Disclosure is per product line. Copying Social Elixir's 21+ age gate onto a nootropic product is
// a compliance error, so an unverified line renders NO small print rather than a borrowed one.
function legalContract(product) {
  const d = DESIGN.disclosures.byLine?.[product.category];
  if (d?.verified && d.text) {
    return `MANDATORY SMALL PRINT, set cleanly at the very bottom in small caps, correctly spelled and fully legible:\n"${d.text}"`;
  }
  return `SMALL PRINT: this product has NO approved disclosure line. Render NO small print, NO legal line, NO age gate and NO disclaimer anywhere in the image. Do not invent one, and do not borrow wording from any other product. Leave that area clean.`;
}

// ---- generation -------------------------------------------------------------------------------
async function gen(brief, ratio, outDir) {
  const product = CATALOG.compounds[brief.product];
  if (!product) return console.log(`x ${brief.name}: unknown product "${brief.product}". Run --list.`);
  const vial = path.join(REPO, product.vial);
  const refs = [vial, LOGO, STYLEREF];
  const missing = refs.filter((f) => !fs.existsSync(f));
  if (missing.length) return console.log(`x ${brief.name}: missing reference art —\n   ${missing.join("\n   ")}`);
  if (!process.env.OPENAI_API_KEY) return console.log(`x ${brief.name}: OPENAI_API_KEY is not set. Add it to .env.`);

  // Surface unresolved facts at run time. A silent guard is one nobody knows to close.
  const pc = CATALOG.packagingCopy[product.category];
  const disc = DESIGN.disclosures.byLine?.[product.category];
  if (pc?.specVerified === false) console.log(`!! ${brief.name}: ${product.name} nutrition figures are UNVERIFIED — the spec panel is being kept out of frame. Confirm them with the client, then set specVerified:true in catalog.json.`);
  if (!disc?.verified) console.log(`!! ${brief.name}: no approved disclosure line for this product line — rendering none. Do NOT reuse another line's age gate. Resolve in design-system.json disclosures.byLine.`);

  const prompt = buildPrompt(brief, product, ratio);
  for (const size of SIZES[ratio]) {
    const form = new FormData();
    form.append("model", "gpt-image-2");
    form.append("prompt", prompt);
    form.append("size", size);
    form.append("quality", "high");
    form.append("n", "1");
    for (const f of refs) form.append("image[]", new Blob([fs.readFileSync(f)], { type: "image/png" }), path.basename(f));
    const res = await fetch("https://api.openai.com/v1/images/edits", {
      method: "POST", headers: { Authorization: `Bearer ${process.env.OPENAI_API_KEY}` }, body: form,
    });
    if (res.ok) {
      const b64 = (await res.json())?.data?.[0]?.b64_json;
      if (!b64) return console.log(`x ${brief.name}: no image in response`);
      fs.mkdirSync(outDir, { recursive: true });
      const out = path.join(outDir, `DialedMoods_${brief.name}_${ratio}.png`);
      fs.writeFileSync(out, Buffer.from(b64, "base64"));
      return console.log(`OK ${ratio} ${brief.name} -> ${path.relative(REPO, out)}`);
    }
    const txt = await res.text();
    if (/size|dimension|pixel|budget|too large/i.test(txt) && size !== SIZES[ratio].at(-1)) {
      console.log(`.. ${brief.name}: ${size} rejected, stepping down`); continue;
    }
    return console.log(`x ${brief.name}: ${res.status} ${txt.slice(0, 300)}`);
  }
}

// ---- entry ------------------------------------------------------------------------------------
const ratio = String(flag("ratio", "4x5"));
if (!SIZES[ratio]) { console.log(`Unknown ratio "${ratio}". Use: ${Object.keys(SIZES).join(", ")}`); process.exit(1); }
const outDir = path.join(REPO, String(flag("outdir", "Dialed Moods Generated")), ratio);

let briefs = [];
if (flag("preset")) {
  const presets = JSON.parse(fs.readFileSync(path.join(REPO, "dialed_moods_presets.json"), "utf-8"));
  const set = presets[String(flag("preset"))];
  if (!set) { console.log(`Unknown preset. Available: ${Object.keys(presets).join(", ")}`); process.exit(1); }
  briefs = set;
} else if (flag("brief")) {
  const j = JSON.parse(fs.readFileSync(String(flag("brief")), "utf-8"));
  briefs = Array.isArray(j) ? j : [j];
} else if (flag("product")) {
  briefs = [{
    name: String(flag("name", "untitled")), product: String(flag("product")),
    eyebrow: String(flag("eyebrow", "DIALED MOODS")), headline: String(flag("headline", "")),
    gold: flag("gold") || "", support: flag("support") ? [String(flag("support"))] : [],
  }];
  if (!briefs[0].headline) { console.log("--headline is required. See --list for products."); process.exit(1); }
} else {
  console.log("Nothing to do. Try --list, --product ..., --brief file.json, or --preset socialElixirLaunch");
  process.exit(1);
}

const only = flag("only");
for (const b of briefs) { if (only && b.name !== only) continue; await gen(b, ratio, outDir); }
console.log("done");
