#!/usr/bin/env node
// Social Elixir launch graphics — the WHOLE graphic generated by gpt-image-2, with the supplied can
// renders passed only as references. No HTML/CSS layer, no compositing (forever rule).
// usage: node dialed_social_elixir_gen.mjs <4x5|9x16> [piece ...]      (gpt-image-2, default)
//        node dialed_social_elixir_gen.mjs <4x5|9x16> --nb [piece ...]  (Nano Banana fallback)
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

// Derived from this file's own location — never hardcode a home directory, it breaks every clone
// but the author's.
const REPO = path.dirname(fileURLToPath(import.meta.url));
const ENV = path.join(REPO, ".env");
if (fs.existsSync(ENV)) {
  for (const line of fs.readFileSync(ENV, "utf-8").split("\n")) {
    const m = line.match(/^\s*([\w]+)\s*=\s*(.+?)\s*$/);
    if (m && !process.env[m[1]]) process.env[m[1]] = m[2];
  }
}
// gpt-image-2 is the preferred path. --nb falls back to Nano Banana, which rendered the approved
// piece and is the safety net if OpenAI is rate/billing limited.
const USE_NB = process.argv.includes("--nb");
const HERE = path.join(REPO, "Dialed Moods Social Elixir");
// Single source of truth for artwork is the brand pack, not this campaign folder. Declared in
// knowledge/brands/dialed-moods/design-system.json under "assets".
const KAVA = path.join(REPO, "Brand Context", "assets", "Dialed_Moods", "creative");
const LOGO = path.join(KAVA, "dialedMoodsLogo.png");
// Downscaled copy of the approved creative, passed as the style anchor so new pieces cannot drift
// off the signed-off look. Regenerate with:
//   sips -Z 1400 style_master_4x5.png --out style_master_ref_1400.png
const STYLEREF = path.join(KAVA, "style_master_ref_1400.png");

// gpt-image-2: sides divisible by 16, longest edge <= 3840, ~8.2MP budget. Descending ladder —
// the first size that the API accepts wins, so a budget rejection costs a retry, not the run.
const AR = { "4x5": "4:5", "9x16": "9:16" };
const SIZES = {
  "4x5": ["2560x3200", "2432x3040", "2048x2560", "1728x2160"],
  "9x16": ["2144x3808", "1920x3408", "1536x2736"],
};
const MODE = process.argv[2] === "9x16" ? "9x16" : "4x5";
const OUT = path.join(HERE, `out_${MODE}`);
fs.mkdirSync(OUT, { recursive: true });

const FL = {
  lemonade: { f: "Lemonade", label: "LEMONADE", ground: "deep near-black charcoal washed with warm gold and amber light" },
  arctic: { f: "ArticBlue", label: "ARCTIC BLUE", ground: "deep midnight navy washed with electric cyan-blue light" },
  mango: { f: "MangoPeach", label: "MANGO PEACH", ground: "deep burnt-umber black washed with warm peach and amber light" },
};

const BRAND = `BRAND AND ART DIRECTION — Dialed Moods, a premium functional-beverage brand.
· REFERENCE 1 is the actual product can. Reproduce it EXACTLY: the same charcoal-grey body, the same pixel-mosaic bands top and bottom, the same bold italic chrome "DIALED" wordmark with its heavy GOLD outline, the small "MOODS", the "SOCIAL ELIXIR" line, "DIETARY SUPPLEMENT", "12 FL OZ (355 ML)", the flavour tab and the fruit artwork. Do not redesign, re-letter or restyle the can or any word printed on it.
· REFERENCE 2 is the Dialed Moods logo — the italic chrome "DIALED" wordmark with a gold outline and "MOODS" at its lower right. Place it as the brand mark, reproduced faithfully, small in the TOP-LEFT corner.
· The can is SHARP, in crisp focus, high-resolution, glossy aluminium with realistic specular highlights and condensation-free clean metal. It is the hero and must never look soft, blurred, upscaled or pasted.
· Palette: charcoal and near-black grounds, ONE metallic gold accent (#D2AC47), cool white type. Premium, cinematic, editorial — like a high-end spirits or performance-drink campaign. Rich gradient light, soft volumetric glow behind the can, subtle film grain, deep contrast.
· Typography: heavy modern geometric sans, tight tracking, sentence case. Type is crisp, perfectly legible, correctly spelled, and NEVER overlaps the can — it sits in clean empty space with generous margins.
· NO ghosted, watermark, oversized or repeated background lettering anywhere. NOT a flyer, NOT clip-art, NOT a collage, no stock-photo people, no rainbow gradients, no neon, no clutter, no watermarks.`;


const TYPEDEPTH = `TYPOGRAPHY MUST LIVE INSIDE THE SCENE — not sit flat on top of it. Build the graphic in real LAYERS, front to back:
· BACK LAYER: atmosphere only — NO text of any kind behind the can. Build the depth with light instead: a soft column of glow, drifting haze and a large out-of-focus gradient bloom that the can partly occludes. Never place a ghosted, oversized or watermark word behind the product.
· That bloom is SOFT-EDGED SMOKE AND LIGHT, never a shape. No hard-edged circle, disc, halo, ring, spotlight cut-out or flat coloured panel behind the can, and no hard horizon line or bright straight streak across the floor. The glow must have no detectable edge — it dissolves into the dark ground exactly like the haze in Reference 3.
· MID LAYER: the can, lit by a single hard key light.
· FRONT LAYER: the headline, sitting forward and crisp.
· The SAME key light rakes across the headline as across the can: the letterforms catch a warm specular highlight along their top-left edges and fall into shadow at the lower right, with a faint gold rim where the light grazes them.
· The headline casts a soft, believable drop shadow onto the surface and background behind it, matching the can's own shadow direction and softness.
· Where the product stands on a glossy surface, the type reflects in it too — a dimmer, blurred, vertically-flipped echo, fading out exactly like the can's reflection.
· Volumetric haze, light bloom and a few soft out-of-focus bokeh motes drift IN FRONT of parts of the type, so atmosphere passes over it and it is not a clean sticker layer.
· The gold words are real brushed metal, not flat colour: a vertical gradient from pale champagne highlight through deep antique gold to a dark bronze base, with a fine bevelled edge and one bright specular streak — the same metal as the can's DIALED outline.
· Let the headline BREAK THE GRID slightly: one line may tuck just behind the can's edge, and the eyebrow may sit on a thin gold rule that runs off the frame.
· Add a faint embossed or debossed treatment to the smallest labels so they read as printed into the surface rather than laid over it.
· Everything stays perfectly legible and correctly spelled. Depth and lighting, never decoration for its own sake.`;

const LEGAL = `MANDATORY SMALL PRINT, set cleanly at the very bottom in small caps, correctly spelled and fully legible:
"NON-ALCOHOLIC · 21+ · ID WILL BE CHECKED"`;

// Renders have shipped "the ocasion.", "BOODS" and "368 ML". Spelling gets its own block at the end
// of the prompt, where it is read last, rather than being one bullet buried in the art direction.
const SPELLING = `FINAL PROOF-READING PASS — DO THIS BEFORE YOU FINISH THE IMAGE:
· Every string I placed inside quotation marks above must appear character-for-character, correctly spelled, with correct punctuation. Copy them letter by letter. Do not paraphrase, re-break, abbreviate or "improve" a single word.
· Watch these specifically: "occasion" has two C's and one S. "BOOZE" ends in ZE. "355 ML". "kavalactones".
· Re-read every word you have drawn — on the type AND on the can — and confirm it is a real, correctly spelled word before you finish. Any garbled, doubled, dropped or invented letter is a failure of the whole image.
· No word may be cut off at the frame edge, and no line may overlap the can.`;

// REFERENCE 3 = the approved piece. This is what keeps 2-5 on the signed-off look instead of
// re-rolling a new art direction every run.
const STYLEMATCH = `REFERENCE 3 IS AN ALREADY-APPROVED PIECE FROM THIS EXACT CAMPAIGN. It is the style master. Match it precisely on all of the following:
· the same near-black graduated ground and the same soft volumetric bloom behind the can — same darkness, same falloff, same drifting haze, but tinted to the colour the brief below specifies, not Reference 3's gold
· the same camera height, the same can scale in frame, the same long glossy floor reflection
· the same single hard key light and the same specular behaviour on both the metal and the type
· the same brushed-metal gold treatment on the accented words
· the same heavy geometric sans, the same tight tracking and sentence case, the same generous left margin and the same vertical rhythm between eyebrow, headline and supporting copy
· the same small Dialed Moods logo in the top-left corner and the same centred small print at the very bottom
· the same overall level of finish, contrast, grain and restraint.
DO NOT copy REFERENCE 3's words, its headline, its flavour, its colour of light or its specific layout content — those come from the brief below and must be different. Reference 3 supplies the LOOK ONLY. This is a sibling in a set, not a duplicate: it must be unmistakably the same campaign and obviously a different post.`;

// The previous session logged this as "hallucinated micro-copy". It is not — REFERENCE 1 genuinely
// carries the app/QR steps, "Prize With Every Can" and the spec column, and the real can already
// reads 20mg. So the rule is faithfulness + a hard numeric lock, NOT erasure: telling the model to
// blank the panel would falsify the packaging, which is worse than soft small print.
const CANFIX = `PRINTED COPY ON THE CAN — REPRODUCE, NEVER INVENT:
· Every word printed on the can must come from REFERENCE 1. Reproduce its side panel as it actually exists — the vertical "Prize With Every Can" line, the QR code and its three numbered app steps, the small "Dialed Health" mark, the tagline and the nutrition column. Do not redesign, re-word or re-letter any of it.
· NUMERIC LOCK: the nutrition column reads EXACTLY 180mg, 200mg, 50mg, 20mg, top to bottom. The fourth value is 20mg sodium. Never 30mg. Never any other figure. If those four numbers cannot be rendered crisply and correctly, turn that panel away from camera instead.
· Where printed type is genuinely too small to letter, let it fall into natural photographic softness — slightly out of focus, low contrast, the way real 4pt pack copy looks in a studio photograph. Do NOT substitute sharp scrambled pseudo-lettering for it.
· Invent nothing that is not on REFERENCE 1: no extra warning block, no extra supplement-facts table, no additional QR code, no new claims.
· THESE EXACT STRINGS APPEAR ON THE CAN AND MUST BE SPELLED CHARACTER-FOR-CHARACTER. Proof-read each one before finishing:
  "UNWIND WITHOUT THE BOOZE"  (in the band under the top mosaic — it is BOOZE. Not BOODS, not DOOZS, not BOOZS)
  "SOCIAL ELIXIR"
  "DIETARY SUPPLEMENT"
  "12 FL OZ (355 ML)"  (it is 355 ML. Never 368, never 80, never any other volume)
  "Prize With Every Can"
  "180mg" "200mg" "50mg" "20mg"  (in that order — magnesium is 50mg, sodium is 20mg)
· ABSOLUTELY DO NOT REDESIGN THE CAN. It keeps its charcoal-grey body, its dense blue/gold PIXEL-MOSAIC BANDS at top and bottom, its big vertical italic chrome "DIALED" wordmark with the heavy gold outline and drop shadow, the small vertical "MOODS", the coloured flavour tab and the fruit artwork. A plain dark can with a small horizontal logo and no mosaic bands is WRONG and must never be produced.`;

const PIECES = {
  "1_announce": {
    fl: "lemonade", shot: "Front",
    brief: `A launch announcement. ONE can standing as a large, sharp hero on the RIGHT side of the frame, lit like a jewel against a ${FL.lemonade.ground}, with a soft golden bloom behind it and a long clean reflection beneath.
The LEFT half is empty, dark, uncluttered space holding, from top to bottom:
· a small gold eyebrow reading "NEW · AUGUST"
· a very large three-line headline reading exactly "Unwind without the booze." with "the booze." in metallic gold
· one short line of body copy reading exactly "A non-alcoholic kava seltzer with a calm you can actually feel."
· a gold pill-shaped button reading exactly "Shop Social Elixir"`,
  },
  "2_whats_in_it": {
    fl: "arctic", shot: "45",
    brief: `An ingredient-spec graphic. ONE can, sharp and large, angled three-quarters on the RIGHT of the frame against a ${FL.arctic.ground} with a cyan bloom behind it.
The LEFT half is empty dark space holding:
· a small gold eyebrow reading "WHAT'S IN IT"
· a large two-line headline reading exactly "Every can, on the label." with "on the label." in metallic gold
· beneath it a clean vertical spec list, each row a large gold number then a white word, separated by thin hairline rules, reading exactly:
  "180mg kavalactones", "200mg potassium", "50mg magnesium", "20mg sodium"
· a single row of small outlined pill badges reading exactly "10 CAL", "ZERO SUGAR", "GLUTEN-FREE", "VEGAN"`,
  },
  "3_how_to_use": {
    fl: "mango", shot: "45",
    brief: `A how-to-drink graphic. ONE can, sharp and large, on the RIGHT of the frame against a ${FL.mango.ground} with a warm peach bloom behind it and frosty cold condensation beading on the metal.
The LEFT half is empty dark space holding:
· a small gold eyebrow reading "HOW TO DRINK IT"
· a large two-line headline reading exactly "Made for the occasion." with "the occasion." in metallic gold
· three numbered steps, each a small gold numeral then a bold white line, reading exactly:
  "01 Chill it hard.", "02 Crack one as the night starts.", "03 One can, one occasion."`,
  },
  "4_why_different": {
    fl: "lemonade", shot: "Front",
    brief: `A positioning graphic. ONE can, sharp and large, on the RIGHT of the frame against a ${FL.lemonade.ground} with a golden bloom behind it.
The LEFT half is empty dark space holding:
· a small gold eyebrow reading "WHY THIS ONE"
· a very large three-line headline reading exactly "Most zero-proof drinks taste like an absence." with "an absence." in metallic gold
· two short stacked lines each behind a thin gold vertical rule, reading exactly "Felt, not implied." and "Drinks clean."`,
  },
  "5_tomorrow_proof": {
    fl: "arctic", shot: "Front",
    brief: `A benefit graphic contrasting tonight with tomorrow morning. ONE can — the SAME can as REFERENCE 1, charcoal-grey with its blue-and-gold pixel-mosaic bands and its big vertical gold-outlined "DIALED" wordmark — standing CENTRED slightly right, rendered LARGE and sharp so it fills most of the middle of the frame and every band and label on it resolves clearly. Ground it against a ${FL.arctic.ground}, with a cool cyan bloom behind it.
Clean empty dark space at the TOP holds a large two-line headline reading exactly "Fun tonight. Functional tomorrow." with "Functional tomorrow." in metallic gold.
Clean empty dark space at the BOTTOM holds two short columns divided by a thin gold rule, reading exactly "TONIGHT — You're in it." and "7:00 AM — You're fine."`,
  },
};

async function gen(name) {
  const p = PIECES[name];
  const vial = path.join(KAVA, `Dialed_Seltzer_Kava_${p.shot}_${FL[p.fl].f}.png`);
  const prompt = `${p.brief}\n\nThe flavour tab on the can reads "${FL[p.fl].label}".\n\n${BRAND}\n\n${STYLEMATCH}\n\n${TYPEDEPTH}\n\n${CANFIX}\n\n${LEGAL}\n\n${SPELLING}`;

  const refs = [vial, LOGO, STYLEREF];
  const missing = refs.filter((fp) => !fs.existsSync(fp));
  if (missing.length) {
    console.log(`x ${name}: missing reference art —\n   ${missing.join("\n   ")}`);
    console.log("   These are declared in knowledge/brands/dialed-moods/design-system.json under \"assets\".");
    return;
  }
  const key = USE_NB ? "GEMINI_API_KEY" : "OPENAI_API_KEY";
  if (!process.env[key]) return console.log(`x ${name}: ${key} is not set. Add it to .env (see .env.example).`);
  const b64 = USE_NB ? await viaNanoBanana(refs, prompt) : await viaGptImage2(name, refs, prompt);
  if (!b64) return;
  const out = path.join(OUT, `SocialElixir_${name}_${MODE}.png`);
  fs.writeFileSync(out, Buffer.from(b64, "base64"));
  console.log(`OK ${MODE} ${name} (${(fs.statSync(out).size / 1048576).toFixed(1)}MB)`);
}

// gpt-image-2 via /v1/images/edits. The refs go in as image[] so the model edits FROM the real can
// and the approved style frame rather than inventing them — that is the whole fidelity strategy.
async function viaGptImage2(name, refs, prompt) {
  for (const size of SIZES[MODE]) {
    const form = new FormData();
    form.append("model", "gpt-image-2");
    form.append("prompt", prompt);
    form.append("size", size);
    form.append("quality", "high");
    form.append("n", "1"); // note: gpt-image-2 rejects input_fidelity — that is a gpt-image-1 param
    for (const fp of refs) {
      form.append("image[]", new Blob([fs.readFileSync(fp)], { type: "image/png" }), path.basename(fp));
    }
    const res = await fetch("https://api.openai.com/v1/images/edits", {
      method: "POST",
      headers: { Authorization: `Bearer ${process.env.OPENAI_API_KEY}` },
      body: form,
    });
    if (res.ok) {
      const j = await res.json();
      const b64 = j?.data?.[0]?.b64_json;
      if (b64) return b64;
      console.log(`x ${name}: no image in response`);
      return null;
    }
    const txt = await res.text();
    // Only a size/budget rejection is worth stepping down for. Billing and auth are terminal.
    if (/size|dimension|pixel|budget|too large/i.test(txt) && size !== SIZES[MODE].at(-1)) {
      console.log(`.. ${name}: ${size} rejected, stepping down`);
      continue;
    }
    console.log(`x ${name}: ${res.status} ${txt.slice(0, 300)}`);
    return null;
  }
  return null;
}

async function viaNanoBanana(refs, prompt) {
  const inline = (fp) => ({ inline_data: { mime_type: "image/png", data: fs.readFileSync(fp).toString("base64") } });
  const body = {
    contents: [{ parts: [...refs.map(inline), { text: prompt }] }],
    generationConfig: { responseModalities: ["TEXT", "IMAGE"], imageConfig: { aspectRatio: AR[MODE], imageSize: "4K" } },
  };
  const res = await fetch(
    "https://generativelanguage.googleapis.com/v1beta/models/gemini-3-pro-image-preview:generateContent",
    { method: "POST", headers: { "Content-Type": "application/json", "x-goog-api-key": process.env.GEMINI_API_KEY }, body: JSON.stringify(body) },
  );
  if (!res.ok) return console.log(`x nb: ${res.status} ${(await res.text()).slice(0, 200)}`), null;
  const parts = (await res.json())?.candidates?.[0]?.content?.parts || [];
  const img = parts.find((q) => q.inline_data || q.inlineData);
  return img ? (img.inline_data || img.inlineData).data : (console.log("x nb: no image"), null);
}

const ids = process.argv.slice(3).filter((a) => a !== "--nb");
for (const id of (ids.length ? ids : Object.keys(PIECES))) await gen(id);
console.log("done");
